name: UhcTools
main: com.martinbrook.uhctools.UhcTools
version: 0.2
description: Useful commands for UHC matches
commands:
 tp:
  description: Teleportation functions
  usage: /tp | /tp player | /tp player destinationplayer | /tp x y z | /tp player x y z
 tpall:
  description: Teleports all non-creative players to you
  usage: /tpall 
 butcher:
  description: Butchers hostile mobs
  usage: /butcher
 tpd:
  description: Teleports to the last death point
  usage: /tpd
 tpl:
  description: Teleports to the last logout location
  usage: /tpl
 tpn:
  description: Teleports to the last notification
  usage: /tpn
 tps:
  description: Teleports to a player's start point
  usage: /tps start-number | playername
 tp0:
  description: Teleports to the overworld spawn point
  usage: /tp0
 setspawn:
  description: Sets the spawn point to your current location
  usage: /setspawn
 gm:
  description: Toggle gamemode between CREATIVE and SURVIVAL.
  usage: /gm
 heal:
  description: Heals a player
  usage: /heal player
 healall:
  description: Heals all players
  usage: /healall
 feed:
  description: Feeds a player
  usage: /feed player
 feedall:
  description: Feeds all players
  usage: /feedall
 clearinv:
  description: Clears a player's inventory
  usage: /clearinv player
 clearinvall:
  description: Clears all players' inventories
  usage: /clearinvall
 renew:
  description: Feeds, heals and clearinvs a player
  usage: /renew player
 renewall:
  description: Renews all players
  usage: /renewall
 cdmatch:
  description: Starts the match countdown
  usage: /cdmatch seconds
 cdpvp:
  description: Starts the PvP countdown
  usage: /cdpvp seconds
 cdwb:
  description: Starts a world border countdown
  usage: /cdwb newradius seconds
 cdc:
  description: Cancels a running countdown
  usage: /cdc
 chatscript:
  description: Plays a chat script from a file, one line per second
  usage: /chatscript filename
 muteall:
  description: Mutes the chat so that nobody can talk except ops
  usage: /muteall on | off
 pvp:
  description: Enables/disabled PvP
  usage: /pvp on | off
 kill:
  description: Command disabled
  usage: /kill
 notify:
  description: Sends a private notification message to an admin
  usage: /notify Message
  alias: n
 n:
  description: Sends a private notification message to an admin
  usage: /n Message
  alias: notify
 match:
  description: Start the match
  usage: /match
 permaday:
  description: Enable/disable permaday
  usage: /permaday on | off
 deathban:
  description: Enable/disable deathban
  usage: /deathban on | off
 clearstarts:
  description: Clear saved start points
  usage: /clearstarts
 loadstarts:
  description: Load start points from disk
  usage: /loadstarts
 savestarts:
  description: Save start points from disk
  usage: /savestarts
 liststarts:
  description: List start points
  usage: /liststarts
 makestart:
  description: Create a start point at the current location
  usage: /makestart
 listplayers:
  description: List all players, and their start points and status
  usage: /listplayers
 launch:
  description: Launch all players, or a specific player
  usage: /launch [player]
 relaunch:
  description: Relaunch a player
  usage: /relaunch player  